In [3]:
import numpy as np
import random

#Inisialise the matrix
matrix = np.zeros((3, 3))

# Randomly choose a starting point
x, y = random.randint(0, 2), random.randint(0, 2)
matrix[x][y] = 1  

# Define the moving deriction
moves = ['up', 'down', 'left', 'right']

# randomly choose a direction
move = random.choice(moves)

# Define the function
def make_move(x, y, move):
    if move == 'up' and x > 0:
        x -= 1
    elif move == 'down' and x < 2:
        x += 1
    elif move == 'left' and y > 0:
        y -= 1
    elif move == 'right' and y < 2:
        y += 1
    return x, y

# implementation
x, y = make_move(x, y, move)


if matrix[x][y] == 0:
    matrix[x][y] = 2  

print(matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 2.]]
